package com.fiap.fastfood.common.exceptions.custom;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum ExceptionCodes {

    PAYMENT_01_NOT_FOUND,
    PAYMENT_02_PAYMENT_CREATION,
    PAYMENT_03_PRODUCT_ID_UNMATCH,
    PAYMENT_04_CUSTOMERID_UNMATCH,
    PAYMENT_05_PRODUCT_PRICE_UNMATCH,
    PAYMENT_06_MESSAGE_CREATION,
    PAYMENT_07_COMMAND_PROCESSING,
    PAYMENT_08_RESPONSE_SAGA,
    PAYMENT_O9_PAYMENT_CHARGE,
    PAYMENT_10_PAYMENT_REVERSE,
    PAYMENT_11_PAYMENT_CANCEL,
}
