apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-postech-fastfood-pagamento
  namespace: fiap-pos-tech
spec:
  selector:
    matchLabels:
      app: fiap-postech-fastfood-pagamento
  replicas: 1
  template:
    metadata:
      labels:
        app: fiap-postech-fastfood-pagamento
    spec:
      containers:
        - name: fiap-postech-fastfood-pagamento
          image: 731362576078.dkr.ecr.us-east-1.amazonaws.com/fiap_postech_fastfood_pagamento:${IMAGE_TAG} #pegar uri do repositório ECR
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"  # Requisição de CPU inicial
              memory: "512Mi"
            limits:
              cpu: "500m"  # Limite de CPU
              memory: "1Gi"
          env:
            - name: MS_PRODUTO_URL
              value: "http://alb-cluster-fiap-2100904419.us-east-1.elb.amazonaws.com"
            - name: MS_CLIENTE_URL
              value: "http://alb-cluster-fiap-2100904419.us-east-1.elb.amazonaws.com"
            - name: MS_PEDIDO_URL
              value: ""
            - name: ACCOUNT_ID
              value: "731362576078"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-postech-service-pagamento
  namespace: fiap-pos-tech
spec:
  type: NodePort
  selector:
    app: fiap-postech-fastfood-pagamento
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010




